# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc07a33cb7bfcca6ef8a1e1f0074e0485dcf95628fcfb7bf8dbcf178047846f53cd425d2261d5720e90e3bdb81b35933231d7d75fdf953e64500346754d1d13e

test:
  secret_key_base: 7ea54e7e31fa0809facae5eabe931e1f84679b0ab36cbe98d3c416bd3eb041b4daee793561e9dd087bac3df6f90ecf6d388d6024affd1b3d53a5eca6d1a72c23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
